### ISSUE TITLE
Ceil function weird behavior

### ISSUE THREAD

**Issue by rogeriopaludo** [aleaxit/gmpy#109]
I'm working with big numbers, both integers and floats. 
The simple case of rounding towards positive infinity using ceil returns:

```
>>> gmpy2.ceil(25852724578493228.946565) 
mpfr('25852724578493228.0')
>>> 
```

Which is rater weird. I've tried to increase precision, up to ridiculous values; didn't solve the problem. 
Running for example, 

```
>>> gmpy2.ceil(28.946565) 
mpfr('29.0')
>>> 
```

is obviously correct. I'm using version 2.0.7 on Linux. I implemented the same code in C, and works like a charm with 5*1024 bits of precision. Master branch presents the same problem. May you please confirm what's the expected behavior?

**Comment by casevh** [comment]
On Mon, Jul 4, 2016 at 9:23 PM, Rogério Paludo <notifications@github.com>
wrote:

> I'm working with big numbers, both integers and floats.
> The simple case of rounding towards positive infinity using ceil returns:
>
> >>> gmpy2.ceil(25852724578493228.946565)
> mpfr('25852724578493228.0')
> >>>
>
> Which is rater weird. I've tried to increase precision, up to ridiculous
> values; didn't solve the problem.
>
The problem is that the argument is is first converted to Python float with
53 bits of precision and then converted to an mpfr. You should initialize
mpfr instances from a string to get the advantaged of extended precision.

# With default precision.
>>> gmpy2.mpfr(25852724578493228.946565)
mpfr('25852724578493228.0')

# With extended precision.
>>> gmpy2.get_context().precision=128

# Note that even with extended precision for mpfr, the correct mpfr value
is only
# obtained when initializing from a string.
>>> gmpy2.mpfr(25852724578493228.946565)
mpfr('25852724578493228.0',128)
>>> gmpy2.mpfr("25852724578493228.946565")
mpfr('25852724578493228.94656499999999999999997',128)
>>> gmpy2.ceil(gmpy2.mpfr("25852724578493228.946565"))
mpfr('25852724578493229.0',128)

casevh

Running for example,

**Comment by rogeriopaludo** [comment]
Owww, I see what the problem was. So you have to make sure you're always assigning mpfr values to mpfr, otherwise you start to have problems like this.
