### ISSUE TITLE
Creating a MPQ_Object from a mpq_t pointer

### ISSUE THREAD

**Issue by marcogario** [aleaxit/gmpy#112]
Hi,

In pySMT [1], we interface with various 3rd party libraries at the C level. Python bindings for those libraries are (usually) not managed by us. 

In some cases the libraries are able to operate on mpq_t objects. I'd like to use gmpy to provide high-level access to those mpq_t objects. In order to do so, I think the easiest way would be to have a factory method in gmpy that creates a MPQ_Object starting from an mpq_t reference. Moreover, I'd need a way to obtain the reference to the mpq_t object in order to make the calls to the underlying library.

Do you think this would be possible? Any pointers or ideas would be great!

Thanks
Marco

[1] https://github.com/pysmt/pysmt

**Comment by casevh** [comment]
gmpy 1.17 includes a C API that can be called from another C extension. For an example, see pysymbolic.c ( https://github.com/aleaxit/gmpy/blob/gmpy_1_17/src/pysymbolicext.c ). It has been several years since I looked at it.

I removed the C API from gmpy2 2.0.x since it was out of date and rarely used. I plan to add a more capable C API in the 2.1 release but that is going slow.

If you need assistance with the C API, let me know and I'll do my best to help.

**Comment by marcogario** [comment]
Thanks for the answer. I integrated (running the final tests now) gmpy2 at the python level in our library. I tried to do it at the C level, by modifying one of the C extensions, and passing directly the  ```MPQ_Object``` and then accessing the ```mpq_t``` object within. This works, but it turns out that the difference in performance between python-level and C-level (for our use case) is negligible... and the C-level solution is quite ugly (imho). Therefore, we decided to keep gmpy2 *only* at the python level.

Thank you for making the mpq object compatible with Fractions! The changes to our code were very minimal, and we now support both options!
