### ISSUE TITLE
Do not call mp_set_memory_functions() if custom functions are already used

### ISSUE THREAD

**Issue by jdemeyer** [aleaxit/gmpy#126]
If some other library has already changed the GMP memory functions, then `gmpy2` should just leave those in place.

**Comment by casevh** [comment]
This should be fixed in the 2.0.9 branch. I'll port it master soon. I no longer attempt to set the memory management functions. I may support changing the memory manager in the future but only for statically linked builds (and likely only for Windows) where the change shouldn't be able to impact any other library.

**Comment by jdemeyer** [comment]
> I no longer attempt to set the memory management functions.

I am not saying that you should just stop setting the memory management functions. You could check whether they are still the default and only then change them.

**Comment by casevh** [comment]
Understood. But I found a subtle bug in the current use of the memory management functions in my first attempt at fixing this so it was easier to just avoid using it. The only purpose was to raise an exception when memory (re)allocation failed instead of just letting GMP abort. There are still other ways that GMP can abort so it wasn't a perfect fix. I may use your suggested approach but I won't have time for a few days.

**Comment by jdemeyer** [comment]
For the record: for my personal purposes, I am happy with this change. So you don't have to change anything for me.
