### ISSUE TITLE
Failures in doctests 'test_gmpy2_mpz_misc' with python 2.7

### ISSUE THREAD

**Issue by vinklein** [aleaxit/gmpy#133]
Rundoctests result is 12 failures  in test_gmpy2_mpz_misc.
Reason looks to be calling  `math.floor`  `math.ceil` or `round` on an object in python2.7 doesnt return the results of the correspoding method `__floor__`, `__ceil__` and `__round__`.

**Comment by casevh** [comment]
In Python 3, the return type of math.floor, math.ceil, and round was changed to an integer instead of a float. The actual value is the same but the type changed. 

gmpy2 returns the corresponding type as the Python version. The tests assume the Python 3 behavior. Fixing the tests is straight-forward but a more important question is "Should gmpy2 follow the behavior of the Python version (primarily 2 vs. 3) or should gmpy2 behave the same across all version?"

Which option do you prefer?

**Comment by vinklein** [comment]
Well both options have their own merits, but i prefer the second one. In my opinion, a module should always return the same types, it's cleaner and clearer for the module users.
