### ISSUE TITLE
Error in addition in windows

### ISSUE THREAD

**Issue by isuruf** [aleaxit/gmpy#147]
```
-2147483648 + mpz(0) != -2147483648
```
This is probably due to converting to `long` after checking `mpz_fits_slong` with mpir. This is on Windows 64bit with mpir, mpfr, mpc, gmpy2 all compiled with MSVC. Note that `long` is 32 bits and `mpir_si` is 64 bits long.

See https://ci.appveyor.com/project/isuruf/gmpy/build/1.0.7/job/owyi7qrjk59adnb3#L144

**Comment by casevh** [comment]
I pushed a commit with following changes:
* defined native_si/native_ui types that correspond to long on most platforms but are long long on 64-bit Windows
* a macro GMPy_Integer_AsNative_siAndError is used to select between GMPy_Integer_AsLongAndError and GMPy_Integer_AsLongLongAndError (similar for the unsigned variants)
* the build option --mpir is currently required (better auto-detection in setup.py would be a good thing)
* mpir.h is used instead of gmp.h

**Comment by isuruf** [comment]
Thanks. I'm not on windows right now. Can you enable appveyor on this repo so that we can see if it fixes this issue?

**Comment by casevh** [comment]
I'll try to get Appveyor enabled tomorrow.

**Comment by isuruf** [comment]
I checked and this error is fixed now.
