### ISSUE TITLE
Slow modulus if divisor is instance of mpz

### ISSUE THREAD

**Issue by stephantul** [aleaxit/gmpy#188]
I'm currently dividing some really big integers using prime numbers, and I have observed that the mod operator is slower if the divisor is an instance of `mpz`. This is contrary to my expectation. Are my numbers too small to take full advantage of the power of `gmpy2`?

I'm running this using:
- Mid 2015 Macbook pro running OSX 10.13
- Python 3.6
- gmpy2 version 2.0.8.
- gmp 6.1.2_2 installed through homebrew.

An example:
```
from gmpy2 import mpz

# Same prime, mpz and regular int
a = mpz('5')
b = 5
num = mpz(5671234 ** 1234)
%timeit num % a
# 1.86 µs ± 21.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
%timeit num % b
# 400 ns ± 7.88 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

# Larger numbers
a = mpz(104729)
b = 104729
%timeit num % a
# 1.84 µs ± 20.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
%timeit num % b
# 406 ns ± 11.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

In both cases, dividing by a regular python int makes it faster. 

`gmpy2` works well, because reverting to regular python ints makes everything slower, as seen in the final example.

```
# Using a regular python int
num_int = int(num)
%timeit num_int % a
3.17 µs ± 46.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
%timeit num_int % b
11.4 µs ± 232 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Please let me know if my expectations were unrealistic, or if I'm doing something wrong.  Thanks!

**Comment by casevh** [comment]
It is the expected behavior. 

GMP frequently has two functions for a given operation. There is a usually a function that accepts `mpz` arguments and a second version that accepts `mpz` and a native C long. When `gmpy2` parses arguments, it tries to take advantage of the two functions when an argument is a Python int.

The logic for mod(xy.) is roughly this:

```
if is_mpz(x):
  if is_python_int(y):
    if fits_in_C_long(y):
      retum mod_mpz_long(x, convert_to_C_long(y))
    else:
      return mod_mpz_mpz(x, convert_to_mpz(y))
  if is_mpz(y):
   return mod_mpz_mpz(x,y)
  do_other_stuff()
```
I just haven't added the extra check on the `is_mpz(y)` path.

Version 2.1 adds support for `is_divisible()`which uses a GMP function which only accepts a C long as the divisor. The performance is the same regardless of whether the divisor is given a Python int or an `mpz`.

If you are performing multiple divisions, you should try multiplying several divisors together and calculating the gcd().

**Comment by stephantul** [comment]
Thanks so much for the swift reply. 

This makes everything a lot clearer. I was afraid I missed some install path or did something wrong regarding installation.
