### ISSUE TITLE
pip install gmpy2 fails for python 3.7 / ubuntu 16.04 

### ISSUE THREAD

**Issue by PorkShoulderHolder** [aleaxit/gmpy#292]
Not sure if I am missing something obvious here but compilation fails with `src/gmpy.c:237:20: fatal error: Python.h: No such file or directory`

libgmp, libmpfr, and libmpc were all installed via apt-get, and this error appears both when I try to install w/ pip and with `python setup.py install`

**Comment by bc-davin** [comment]
This is a bug in gmpy2 2.0.x series. It has been fixed in the currently development version. gmpy2 2.1.0a2 is available on PyPi but is hidden. The following commands will install it in a user-specific directory. Python will load modules from the user-specific directory first so the new version will shadow the provided version. 

Try 

sudo apt install libmpc-dev
sudo apt install python3-pip
pip3 install --user gmpy2==2.1.0a2

**Comment by PorkShoulderHolder** [comment]
Fixed with `apt-get install python3.7-dev` in my case. In the general case just use an analogous command to update the headers of the specific version of python you are using.
